apiVersion: v1
kind: Service
metadata:
  name: backend-staging-service
spec:
  type: NodePort
  selector:
    app: backend
    env: staging
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30001
