apiVersion: v1
kind: Service
metadata:
  name: backend-production-service
spec:
  type: NodePort
  selector:
    app: backend
    env: production
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30007
