name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Docker Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Backend Docker Image
        run: docker build -t rowda94/easyorder24-backend:latest ./backend

      - name: Build Frontend Docker Image
        run: docker build -t rowda94/easyorder24-frontend:latest ./frontend

      - name: Push Docker Images
        run: |
          docker push rowda94/easyorder24-backend:latest
          docker push rowda94/easyorder24-frontend:latest

  test:
    name: Run Unit and Integration Tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run Backend Tests
        run: |
          cd backend
          pip install -r requirements.txt
          pytest

      - name: Run Frontend Tests
        run: |
          cd frontend
          npm install
          npm test

  staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy Backend to Staging
        run: |
          kubectl apply -f backend/deployment.yaml
          kubectl apply -f backend/service.yaml

      - name: Deploy Frontend to Staging
        run: |
          kubectl apply -f frontend/deployment.yaml
          kubectl apply -f frontend/service.yaml

  production:
    name: Deploy to Production (Canary)
    runs-on: ubuntu-latest
    needs: staging
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy Backend Canary
        run: kubectl apply -f backend/canary-deployment.yaml

      - name: Deploy Frontend Canary
        run: kubectl apply -f frontend/canary-deployment.yaml






