name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Run flake8 (soft fail)
        run: |
          flake8 backend || echo "Flake8 warnings detected, continuing pipeline"

      - name: Run tests (soft fail)
        run: |
          pytest backend/ || echo "Tests failed or no tests found, continuing pipeline"

  build-docker:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t easyorder24-backend backend/

  docker-test:
    runs-on: ubuntu-latest
    needs: build-docker
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run Docker container
        run: |
          docker run --rm -d -p 5000:5000 --name backend easyorder24-backend
          echo "Waiting for container to start..."
          sleep 10
          curl -f http://localhost:5000 || echo "Container not responding yet"
          docker stop backend || echo "Container already stopped"

  deploy:
    runs-on: ubuntu-latest
    needs: docker-test
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy placeholder
        run: |
          echo "Hier könnte die Bereitstellung in eine Staging- oder Produktionsumgebung erfolgen."
          echo "CI/CD Pipeline ist erfolgreich durchgelaufen."

