name: Backend CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PAT }}

    - name: Build Backend Docker Image
      run: docker build -t rowda94/easyorder24-backend:latest ./backend

    - name: Push Backend Docker Image
      run: docker push rowda94/easyorder24-backend:latest

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r ./backend/requirements.txt

    - name: Run Unit Tests
      run: |
        pytest ./backend/tests

  staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Configure Kubeconfig
      run: echo "${{ secrets.KUBECONFIG_STAGING }}" > kubeconfig && export KUBECONFIG=kubeconfig

    - name: Deploy Backend to Staging
      run: kubectl apply -f ./backend/k8s/staging-deployment.yaml

  production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: staging

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Configure Kubeconfig
      run: echo "${{ secrets.KUBECONFIG_PRODUCTION }}" > kubeconfig && export KUBECONFIG=kubeconfig

    - name: Deploy Backend to Production
      run: kubectl apply -f ./backend/k8s/production-deployment.yaml





