name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run flake8
        run: flake8 backend || echo "Lint warnings detected, but continuing workflow"

  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
          pip install pytest

      - name: Run Pytest
        run: |
          pytest backend || echo "Tests failed, but continuing workflow"

  build-docker:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t easyorder24-backend ./backend

      - name: Run Docker container (test)
        run: |
          docker run --rm easyorder24-backend

  docker-push:
    name: Push Docker Image (optional)
    runs-on: ubuntu-latest
    needs: build-docker
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          docker tag easyorder24-backend yourdockerhubusername/easyorder24-backend:latest
          docker push yourdockerhubusername/easyorder24-backend:latest

  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: docker-push
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy placeholder
        run: |
          echo "Hier könntest du das Deployment auf eine Test-/Staging-Umgebung durchführen"


      - name: Run Docker container
        run: docker run --rm easyorder24-backend
