name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Run flake8 (nur Warnungen)
        run: |
          flake8 backend || echo "flake8 found issues, but continuing..."

      - name: Run pytest
        run: |
          pytest backend || echo "Tests finished (keine Fehler blockieren den Build)"

  build-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t easyorder24-backend backend/

      - name: Run Docker container
        run: |
          docker run --rm -d -p 5000:5000 --name backend easyorder24-backend
          echo "Waiting for container to start..."
          sleep 10
          curl -f http://localhost:5000 || echo "Container not responding yet"
          docker stop backend || echo "Container already stopped"

  deploy:
    runs-on: ubuntu-latest
    needs: build-docker
    steps:
      - name: Deploy placeholder
        run: |
          echo "Hier könnte ein Deployment in Dev/Staging/Prod stehen"


