name: CI/CD Backend

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      # Code aus dem Repo auschecken
      - name: Checkout repository
        uses: actions/checkout@v3

      # Python installieren
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      # Abhängigkeiten installieren
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
          pip install pytest

      # Unit- und Integrationstests ausführen
      - name: Run tests
        run: pytest ./backend/tests

      # Docker login
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Docker image bauen
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/easyorder24-backend:latest ./backend

      # Docker image pushen
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/easyorder24-backend:latest

      # Monitoring/Feedback (Beispiel: Ausgabe von Status)
      - name: Pipeline Feedback
        run: echo "Build, Tests und Docker Push erfolgreich abgeschlossen"




